### PR TITLE
Added package for realtek 8188eu and 8188eus wifi adapters

### PR DESCRIPTION
**Pull request by vlatkokaplan**
Hello jernejsk, i had one of those 8188eus wifi adapters, and after some testing i found out that this driver package works perfectly with my OPi-PC.

### CODE REVIEW

**Comment by jernejsk** [comment]
Could you please add driver also in ADDITIONAL_DRIVERS variable located at projects/H3/options so it would be automatically included in image?

**Comment by vlatkokaplan** [comment]
You mean in distributions/OpenELEC/options ?

**Comment by jernejsk** [comment]
No, I really mean in projects/H3/options. Variable is in both files, but I want to leave non project files intact as much as possible for easier merging.

**Comment by jernejsk** [comment]
Granted, it is already changed. I will accept it anyway.

**Comment by vlatkokaplan** [comment]
Awesome!

**Pull request merged**
