### PR TITLE
Switch to SLUB allocator as it became the default allocator since 2.6…

### PR DESCRIPTION
**Pull request by Ntemis**
….23!

(and gives better performance too)

### CODE REVIEW

**Comment by jernejsk** [comment]
Did you thoroughly test this? Last time I set it to SLUB, kernel didn't boot. But this was with previous kernel.

And there are also such posts: https://lists.debian.org/debian-kernel/2012/03/msg00944.html

**Comment by Ntemis** [comment]
Please test and merge/or not, accordingly.
What boards are affected by this?
I only have PiPC

**Comment by jernejsk** [comment]
Currently only working board I have is OPi2. This will have to wait a bit, currently I want to improve/redesign renderer code.

**Comment by Ntemis** [comment]
Sure take your time and kudos for an awesome work. 2TU

**Pull request closed without merging**
